### ISSUE TITLE
stoppoll

### ISSUE THREAD

**Issue by shuynh84** [Gambiit/mcp3008.js#2]
I'm pretty new to node-red so I apologize for asking beginner question. The node is giving me an error called pollstop.

Also in the direction, what do you mean by

Just push msg = {payload : start | stop} to start | stop the flow.

do you mean by using the inject button with string?

**Comment by Gambiit** [comment]
It's not an error. It's the default message when the node is in a stop state.
And you're right. You have to use the inject button with string "start" in the payload... to start the node. And normally, the node connected to the spi interface with the intervall you have defined.

**Comment by shuynh84** [comment]
Sorry to be a newbie at this. Do you happen to have any example I can follow by any chance? I've tried injecting msg = {payload : "start"} but nothing happens. Also, I'm not sure what you mean by spi interface? like an spi node?

**Comment by Gambiit** [comment]
Excuse me: I am not fluent to write in English. So you have to read SPI "bus" instead of "interface". Mcp3008 is an electronic component that converts an analog signal into a digital signal. You can connect it to a raspberry pi B or B + because this board has a SPI interface. Read https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md. I made an example that you can check here https://github.com/Gambiit/mcp3008example ... but that was three years ago. I will try to add images to better explain.
